export const languages = [
  "Instrumental",
  "Albanian",
  "Arabic",
  "Aymara",
  "Quechua",
  "Bengali",
  "Berber",
  "Catalan",
  "Chichewa",
  "Croatian",
  "Dutch",
  "English",
  "French",
  "Fula",
  "Gbe",
  "German",
  "Greek",
  "Hausa",
  "Hindi",
  "Italian",
  "Kikongo",
  "Korean",
  "Lingala",
  "Malay",
  "Mandarin Chinese",
  "Manding",
  "Persian",
  "Portuguese",
  "Romanian",
  "Russian",
  "Samoan",
  "Serbian",
  "Slovak",
  "Somali",
  "Songhay-Zarma",
  "Soninke",
  "Sotho",
  "Spanish",
  "Swahili",
  "Swati",
  "Swedish",
  "Tamasheq",
  "Tamil",
  "Tigrinya",
  "Tswana",
  "Turkish",
  "Ukrainian",
  "Venda",
  "Wolof",
  "Xhosa"
];

export const genres = [
  "Alternative Rock",
  "Ambient",
  "Breakcore",
  "Classical",
  "Country",
  "Dance & EDM",
  "Dancehall",
  "Deep House",
  "Disco",
  "Drum & Bass",
  "Electronic",
  "Folk & Singer-Songwriter",
  "Hardcore Techno",
  "Hardstyle",
  "Happy Hardcore",
  "Hip-hop & Rap",
  "House",
  "Indie",
  "Jazz & Blues",
  "Latin",
  "Metal",
  "Piano",
  "Podcast",
  "Pop",
  "R&B & Soul",
  "Raw Hardstyle",
  "Reggae",
  "Reggaeton",
  "Rock",
  "Soundtrack",
  "Techno",
  "Trance",
  "World",
  "Adult Contemporary",
  "Beats & Instrumentals",
  "Downtempo",
  "Emo",
  "Experimental",
  "Ethnic",
  "Industrial",
  "Theatrical & Moody",
  "Meditation",
  "Oldies",
  "Remixes",
  "Live Recordings",
  "Vocals & Acapela",
  "Sounds & FX"
].sort();

export const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burma",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cabo Verde",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Democratic Republic of the Congo",
  "Republic of the Congo",
  "Costa Rica",
  "Cote d'Ivoire",
  "Croatia",
  "Cuba",
  "Curacao",
  "Cyprus",
  "Czechia",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Holy See",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "North Korea",
  "South Korea",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macau",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestinian Territories",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe"
];

export const regions = [
  "North Africa",
  "East Africa",
  "Central Africa",
  "Southern Africa",
  "West Africa",

  "Australia",
  "Pacific Islands",

  "North Asia",
  "East Asia",
  "Central Asia",
  "South Asia",
  "Western Asia",
  "Southeast Asia",

  "Northern Europe",
  "Eastern Europe",
  "Southern Europe",
  "Western Europe",

  "North America",
  "Central America",
  "South America"
].concat(countries);

export const moods = [
  "aggressive",
  "ambient",
  "angry",
  "bouncy",
  "calming",
  "carefree",
  "cheerful",
  "cold",
  "complex",
  "cool",
  "dark",
  "disturbing",
  "dramatic",
  "dreamy",
  "eerie",
  "elegant",
  "energetic",
  "enthusiastic",
  "epic",
  "fun",
  "funky",
  "futuristic",
  "gentle",
  "gleeful",
  "gloomy",
  "groovy",
  "happy",
  "harsh",
  "haunting",
  "humorous",
  "hypnotic",
  "industrial",
  "intense",
  "intimate",
  "joyous",
  "laid-back",
  "light",
  "lively",
  "manic",
  "mellow",
  "mystical",
  "ominous",
  "passionate",
  "pastoral",
  "peaceful",
  "playful",
  "poignant",
  "quiet",
  "rebellious",
  "reflective",
  "romantic",
  "rowdy",
  "sad",
  "sentimental",
  "sexy",
  "smooth",
  "soothing",
  "sophisticated",
  "spacey",
  "spiritual",
  "strange",
  "sweet",
  "theater",
  "trippy",
  "warm",
  "whimsical"
];
